# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1cIcTiL13-0tpkyY1D-SkV20B2oo-uB
"""

import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dense, Dropout
from tensorflow.keras.optimizers import Adam

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Twitter_Data.csv")
df.head()

df = df[['text','sentiment']]

df.dropna(inplace=True)

df.head()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)       # Remove URLs
    text = re.sub(r"@\w+", "", text)          # Remove mentions
    text = re.sub(r"#\w+", "", text)          # Remove hashtags
    text = re.sub(r"[^\w\s]", "", text)       # Remove punctuation
    text = re.sub(r"\d+", "", text)           # Remove numbers
    return text

df['text'] = df['text'].apply(clean_text)

label_encoder = LabelEncoder()
df['sentiment'] = label_encoder.fit_transform(df['sentiment'])

# Check mapping
print(label_encoder.classes_)

X = df['text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

max_words = 10000
max_len = 50

tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len, padding='post')

!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

embedding_index = {}

with open("glove.6B.100d.txt", encoding="utf8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype="float32")
        embedding_index[word] = vector

EMBEDDING_DIM = 100
word_index = tokenizer.word_index

embedding_matrix = np.zeros((max_words, EMBEDDING_DIM))

for word, idx in word_index.items():
    if idx < max_words:
        vector = embedding_index.get(word)
        if vector is not None:
            embedding_matrix[idx] = vector

"""MODEL 1: GloVe + LSTM"""

lstm_model = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=EMBEDDING_DIM,
        weights=[embedding_matrix],
        input_length=max_len,
        trainable=True
    ),
    LSTM(128),
    Dropout(0.5),
    Dense(64, activation="relu"),
    Dense(3, activation="softmax")
])

lstm_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

lstm_model.summary()

lstm_model.fit(
    X_train_pad, y_train,
    epochs=5,
    batch_size=128,
    validation_split=0.2
)

lstm_model.evaluate(X_test_pad, y_test)

"""MODEL 2: GloVe + GRU"""

gru_model = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=EMBEDDING_DIM,
        weights=[embedding_matrix],
        input_length=max_len,
        trainable=False
    ),
    GRU(128),
    Dropout(0.5),
    Dense(64, activation="relu"),
    Dense(3, activation="softmax")
])

gru_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

gru_model.summary()

gru_model.fit(
    X_train_pad, y_train,
    epochs=5,
    batch_size=128,
    validation_split=0.2
)

gru_model.evaluate(X_test_pad, y_test)

from tensorflow.keras.layers import Bidirectional

gru_model_bidriectional = Sequential([
    Embedding(
        input_dim=max_words,
        output_dim=EMBEDDING_DIM,
        weights=[embedding_matrix],
        trainable=True
    ),
    Bidirectional(GRU(128)),
    Dropout(0.5),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(3, activation="softmax")
])

gru_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

gru_model.fit(
    X_train_pad, y_train,
    epochs = 5,
    batch_size = 128,
    validation_split = 0.2
)

gru_model.evaluate(X_test_pad, y_test)

import pickle
print("Saving model and preprocessing files...")

# Save model
gru_model_bidriectional.save("model.h5")

# Save tokenizer
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

# Save label encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

print("All files saved successfully!")
print("model.h5")
print("tokenizer.pkl")
print("label_encoder.pkl")







